### ISSUE TITLE
How to use aligned bam as input rather than fastqs

### ISSUE THREAD

**Issue by smf96** [epi2me-labs/wf-cas9#2]
### What happened?

Hello,

I've recently started using the epi2me cas9 enrichment workflow on my university HPC system. I can get the test data to work using the command:

```
./nextflow run epi2me-labs/wf-cas9 --fastq test_data/fastq --ref_genome test_data/grch38/grch38_chr19_22.fa.gz --targets test_data/targets.bed --full_report --disable_ping true --threads 4 -profile conda -resume
```

Is it possible to use my own aligned bam as input? I already have all my runs mapped using minimap2 with specific parameters that I'd like to use. I'm not that familiar with nextflow syntax, how could I tweak the workflow to use my bam files instead?

Apologies if this is the wrong place to ask but I have posted in ONT community pages but haven't heard anything back yet.

Thank you

### Operating System

ubuntu 20.04

### Workflow Execution

Command line

### Workflow Execution - Execution Profile

Conda

### Workflow Version

v22.04.5

### Relevant log output

```shell
N/A
```

**Comment by sarahjeeeze** [comment]
closing, as we won't be adding for now.
